import { mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { afterEach, expect, test, vi } from 'vitest';
import { installSnippetTemplates, refreshNativeSnippets } from '../src/snippets';
import { readFileStyle } from '../src/file-style';
import { compileStyle } from '../src/style-modules';
import { addHack, removeHack } from '../src/hacks';
const dirs: string[] = [];
afterEach(async () => { await Promise.all(dirs.splice(0).map(d => rm(d, { recursive: true, force: true }))); });
test('shipped installation starts empty and styling appears only after applying a technique', async () => {
 const dir = await mkdtemp(path.join(tmpdir(), 'hacksidian-clean-')); dirs.push(dir);
 const root = path.resolve(import.meta.dirname, '../../snippets');
 const manifestText = await readFile(path.join(root, 'hacksidian-manifest.json'), 'utf8');
 const manifest = JSON.parse(manifestText);
 const templates: Record<string, string> = { 'hacksidian-manifest.json': manifestText };
 for (const entry of manifest.modules) templates[entry.file] = await readFile(path.join(root, entry.file), 'utf8');
 expect(await installSnippetTemplates(dir, templates)).toEqual(manifest.modules.map((entry: { file: string }) => entry.file.slice(0, -4)));
 const style = await readFileStyle(dir);
 expect(style.modules.length).toBe(manifest.modules.length);
 expect(compileStyle(style)).toBe('');
 const hack = { id: 'test-reading', title: 'Test', path: '', spec: { format: 2, target: 'g-metadata', hasCss: true }, css: 'body { --metadata-display-reading: none; }\n' };
 const applied = addHack(style, hack);
 expect(applied.changed).toBe(true);
 expect(compileStyle(applied.style)).toContain(hack.css);
 expect(applied.style.modules.filter(m => m.css)).toHaveLength(1);
 expect(compileStyle(removeHack(applied.style, hack.id).style).trim()).toBe('');
 await writeFile(path.join(dir, 'hacksidian-00-palette.css'), 'body { --text-normal: red; }');
 expect(await installSnippetTemplates(dir, templates)).toEqual([]);
 expect(await readFile(path.join(dir, 'hacksidian-00-palette.css'), 'utf8')).toBe('body { --text-normal: red; }');
});
test('initial seeding preserves existing user bytes and adds only absent templates', async () => {
 const dir = await mkdtemp(path.join(tmpdir(), 'hacksidian-seed-')); dirs.push(dir);
 await writeFile(path.join(dir, 'hacksidian-00-settings.css'), '/* user settings */');
 await writeFile(path.join(dir, 'unrelated.css'), '/* unrelated */');
 const templates = { 'hacksidian-00-settings.css': '/* default */', 'hacksidian-10-reading.css': '/* reading */', 'hacksidian-manifest.json': '{}' };
 expect(await installSnippetTemplates(dir, templates)).toEqual(['hacksidian-10-reading']);
 expect(await readFile(path.join(dir, 'hacksidian-00-settings.css'), 'utf8')).toBe('/* user settings */');
 expect(await readFile(path.join(dir, 'hacksidian-10-reading.css'), 'utf8')).toBe('/* reading */');
 expect(await readFile(path.join(dir, 'unrelated.css'), 'utf8')).toBe('/* unrelated */');
 expect(templates['hacksidian-00-settings.css']).toBe('/* default */');
});
test('native refresh respects disabled snippets and custom configuration directory', async () => {
 const manager = { readSnippets: vi.fn(), loadSnippets: vi.fn(), setCssEnabledStatus: vi.fn(), csscache: new Map([['custom/snippets/hacksidian-00-settings.css', 'old'], ['custom/snippets/other.css', 'keep']]) };
 await refreshNativeSnippets({ vault: { configDir: 'custom' }, customCss: manager } as any);
 expect(manager.setCssEnabledStatus).not.toHaveBeenCalled();
 expect([...manager.csscache.values()]).toEqual(['keep']);
 expect(manager.loadSnippets).toHaveBeenCalledOnce();
 await refreshNativeSnippets({ vault: { configDir: 'custom' }, customCss: manager } as any, ['hacksidian-00-settings']);
 expect(manager.setCssEnabledStatus).toHaveBeenCalledWith('hacksidian-00-settings', true);
});
