throw new Error('Retired: technique cards are maintained as Markdown. This command would recreate technical files or overwrite authored content.');
import {writeCard} from '../card-format.mjs';
import fs from 'node:fs';import path from 'node:path';import {parse,stringify} from '../../plugin/node_modules/yaml/dist/index.js';
const project=path.resolve(new URL('../..',import.meta.url).pathname),dir=path.join(project,'docs/research/theme-survey');
const atlas=process.argv[2]||'/Users/op/vaults/op/! P R O/hacksidian/atlas';
const themes=JSON.parse(fs.readFileSync(path.join(project,'tools/theme-catalog/themes.json'))).themes;
const findings=JSON.parse(fs.readFileSync(path.join(dir,'findings.json'))),coverage=JSON.parse(fs.readFileSync(path.join(dir,'coverage.json'))),defs=JSON.parse(fs.readFileSync(path.join(project,'tools/theme-survey/features.json')));
const decisions=JSON.parse(fs.readFileSync(path.join(dir,'decisions.json')));
const outcomes={'catalog-mapped':'Есть карточка','reviewed-palette':'Палитра','reviewed-preset':'Вариант оформления','reviewed-typography-parameter':'Типографический параметр','reviewed-documentation-control':'Служебная настройка','reviewed-no-current-implementation':'Переключатель не подтверждён CSS'};
const byTheme=new Map(themes.map(t=>[t.slug,t]));
const titles=new Map(defs.filter(d=>d.id).map(d=>[d.id,d.title]));
const title=id=>{if(!titles.has(id)){const text=fs.readFileSync(path.join(atlas,'! hacks',id,id+'.md'),'utf8');titles.set(id,parse(text.match(/^---\n([\s\S]*?)\n---/)[1]).title??id);}return titles.get(id);};
const link=t=>`[[atlas/! themes/${t.slug}|${t.name}]]`;
const escape=s=>String(s).replaceAll('|','\\|').replace(/\r?\n/g,' ');
const evidence=xs=>xs.map(f=>`- ${link(byTheme.get(f.theme))}${f.setting?`: **${f.title}** (\`${f.setting}\`)`:(f.usage?': описанный автором способ применения':': правило CSS без отдельного переключателя')} — [${f.setting?'описание настройки':f.usage?'руководство':'исходник'}](${f.source}), [реализация](${f.implementation}).\n  Селектор: \`${f.selector.replace(/\s+/g,' ').replaceAll('`','').slice(0,1500)}\`.${f.recoveredCss?'\n  Правило восстановлено отдельным разбором после ошибки CSS; внешние условия и каскад проверяйте по исходнику.':''}${f.conditions?.length?'\n  Условия CSS: '+f.conditions.map(c=>'`'+c.replaceAll('`','')+'`').join('; '):''}${f.matchedProperty?'\n  Проверяемое свойство: `'+f.matchedProperty+'`.':''}${f.usage?'\n  Применение: '+f.usage:''}${f.options?.length?'\n  Варианты: '+f.options.map(o=>typeof o==='string'?o:`${o.label} (${o.value})`).join('; '):''}`).join('\n');
const uniqueThemes=xs=>[...new Set(xs.map(f=>f.theme))].map(s=>byTheme.get(s));
let added=0,updated=0;
for(const id of new Set(findings.map(f=>f.id))){
 const xs=findings.filter(f=>f.id===id),existing=xs[0].existing,def=defs.find(f=>f.id===id);
 const folder=path.join(atlas,'! hacks',id),file=path.join(folder,id+'.md');
 const linked=uniqueThemes(xs),sources=[...new Set(xs.flatMap(f=>[f.source,f.implementation]))];
 if(existing){
  const original=fs.readFileSync(file,'utf8'),m=original.match(/^---\n([\s\S]*?)\n---/);if(!m)throw Error(id);
  const meta=parse(m[1]),body=original.slice(m[0].length);
  meta.themes=[...new Set([...(meta.themes??[]),...linked.map(t=>t.slug)])];
  // Preserve original source lists verbatim. New evidence has its own section, with pinned links.
  const marker='\n## Подтверждения в темах — исследование 2026-09-16\n';
  const cleanBody=body.includes(marker)?body.slice(0,body.indexOf(marker)):body;
  // Surgical replacement only of the newly introduced field; no unrelated metadata rewrite.
  const front=m[1].replace(/^themes:.*(?:\n(?:[ \t]+.*|- .*))*\n?/m,'').replace(/\s+$/,'');
  const result='---\n'+front+'\n'+stringify({themes:meta.themes}).trimEnd()+'\n---'+cleanBody+marker+'\nНиже подтверждено присутствие механизма в исходниках темы, не тождественность всех деталей с рецептом атласа. Указаны условия селектора; некоторые варианты включаются настройкой или классом. Проверка отрисовки в текущем Obsidian не проводилась.\n\n'+evidence(xs)+'\n';
  writeCard(file,result);updated++;
 }else{
  if(fs.existsSync(file)&&!fs.readFileSync(file,'utf8').includes('theme-survey-2026-09-16'))throw Error('Refuse to overwrite existing technique '+id);
  fs.mkdirSync(folder,{recursive:true});
  const meta={tags:['hacksidian_technique','hacksidian_'+def.category],title:def.title,category:def.category,sources,format:'markdown',themes:linked.map(t=>t.slug),research:'theme-survey-2026-09-16',implementation:'theme-native',verification:'source-only'};
  const body=`# ${def.title}\n\n## Зачем\n\n${def.why}\n\n## Как использовать\n\nЭто возможность перечисленных тем, а не готовый независимый CSS-сниппет. Откройте карточку темы и её страницу Obsidian Community. Если хотите попробовать приём, установите одну из этих тем вручную; для перечисленных настроек понадобится плагин Style Settings.\n\nЕсли указан пример разметки или класс заметки, используйте его по инструкции соответствующей темы. Если есть настройка — найдите её по точному названию ниже. У переключателей Disable/Hide/Remove направление может быть обратным: их включение нередко отключает эффект. Варианты CSS без переключателя действуют по указанным селекторам и условиям; нельзя автоматически считать их включёнными для любой заметки.\n\n## Чем отличается от существующих приёмов\n\n${def.difference}\n\n## Встречается в темах\n\n${linked.map(t=>'- '+link(t)).join('\n')}\n\n## Подтверждения и настройки\n\n${evidence(xs)}\n\n## Ограничения\n\n${def.limitations??'Точный вид, условия активации и поддерживаемые режимы зависят от выбранной темы.'} Меняется тема хранилища целиком. Проверены исходники на зафиксированных commit; визуальная проверка в установленном Obsidian не проводилась. Старые селекторы CodeMirror могут относиться к прежним версиям редактора.\n\nНезависимый перенос в Hacksidian потребует отдельной адаптации и проверки. CSS авторов не скопирован в применяемый рецепт. При будущем переносе нужно сохранить авторство и выполнить условия лицензии конкретного источника.\n\n## Источники\n\n${linked.map(t=>`- [${t.name} — ${t.author}](https://github.com/${t.repo}) · [Obsidian Community](${t.community_url})`).join('\n')}\n\n[[atlas/! themes/_research/! обзор|Исследование 100 тем]] · [[atlas/atlas|Атлас]]\n`;
  writeCard(file,'---\n'+stringify(meta)+'---\n\n'+body);
  fs.writeFileSync(path.join(folder,'recipe.css'),'');
  fs.writeFileSync(path.join(folder,'hack.json'),JSON.stringify({format:2,target:'g-'+def.category,hasCss:false,requirements:['Одна из указанных тем Obsidian; для настройки — Style Settings','Проверено по исходникам, без визуальной проверки'],group:def.category},null,2)+'\n');added++;
 }
}
const research=path.join(atlas,'! themes','_research');fs.mkdirSync(research,{recursive:true});
for(const t of coverage){
 const xs=findings.filter(f=>f.theme===t.slug),news=[...new Set(xs.filter(f=>!f.existing).map(f=>f.id))],olds=[...new Set(xs.filter(f=>f.existing).map(f=>f.id))];
 const sourceRoot=`https://github.com/${t.repo}/tree/${t.commit}`;
 const settings=t.settings.filter(s=>s.type==='class-toggle'||s.type==='class-select');
 const docs=t.docs.map(d=>`- [${d.file}](${sourceRoot}/${d.file.split('/').map(encodeURIComponent).join('/')})${d.headings.length?' — '+d.headings.map(h=>h.text.replace(/^#+\s*/, '')).join('; '):''}`).join('\n');
 const body=`# Разбор: ${t.name}\n\n${link(byTheme.get(t.slug))} · [Репозиторий на момент проверки](${sourceRoot})\n\nCommit: \`${t.commit}\`. Основной файл: \`${t.primary}\`. Текстовых файлов в инвентаризации: ${t.files}; документов: ${t.docs.length}; CSS-файлов: ${t.cssFiles}; правил основного CSS разобрано: ${t.ruleCount}.\n\n## Результат сопоставления\n\nНовых карточек: ${news.length}; ранее существовавших приёмов с найденными подтверждениями: ${olds.length}.\n\n${[...news,...olds].map(id=>`- [[atlas/! hacks/${id}/${id}|${title(id)}]] — ${news.includes(id)?'новая карточка':'существующая карточка'}`).join('\n')||'Отдельных механизмов сверх палитры в проверенном основном CSS не найдено. Тема остаётся самостоятельным источником рекомендаций по цвету.'}\n\n## Реестр настроек\n\nЭто полный извлечённый список переключателей и вариантов основного CSS. Не каждая настройка является новым приёмом: здесь есть палитры, параметры уже известных механизмов, служебные пункты и варианты оформления плагинов. Каждый переключатель получил результат. Наличие карточки подтверждает общий механизм, а не полное совпадение внешнего вида.\n\n| Настройка | ID | Результат | Обоснование / карточки | Источник |\n|---|---|---|---|---|\n${settings.map(s=>`| ${escape(s.title)} | \`${s.id}\` | ${outcomes[s.disposition]??s.disposition} | ${escape(s.reviewReason??'Подтверждено правилом CSS.')} ${[...new Set(xs.filter(f=>f.setting===s.id).map(f=>f.id))].map(id=>'[[atlas/! hacks/'+id+'/'+id+'\\|'+(title(id))+']]').join('; ')} | [код](${s.source}) |`).join('\n')}\n\n## Документация в репозитории\n\n${docs||'Markdown-документы в репозитории не найдены.'}\n\n## Границы проверки\n\nВыполнены инвентаризация документации, извлечение настроек и разбор CSS. Подтверждения в карточках требуют одновременно объявления настройки и применяющего её правила либо явного CSS-механизма. Скриншоты, внешние сайты документации и отдельные demo-vault не просмотрены полностью; поведение на устройстве не проверено. Разбор всех извлечённых переключателей и списков вариантов завершён. Числовые, цветовые и текстовые параметры и заголовки разделов отдельно сохранены в coverage.json; они не считаются новыми приёмами сами по себе.\n\n${t.parseErrors.length?'Строгий парсер основного CSS встретил ошибки; использован отдельный разбор корректных правил, проблемные места не считаются подтверждением.\n\n'+t.parseErrors.map(e=>'- '+e).join('\n'):''}\n${t.settingsErrors.length?'Для отдельных блоков настроек потребовалось извлечение строк после ошибки YAML; такие строки также получили итоговый результат; наличие настройки без применяющего её правила не засчитывается как подтверждение.':''}\n\n[[atlas/! themes/_research/! обзор|Общий обзор]]\n`;
 fs.writeFileSync(path.join(research,t.slug+'.md'),body);
 const card=path.join(atlas,'! themes',t.slug+'.md');let text=fs.readFileSync(card,'utf8');const marker='\n## Исследование приёмов\n';if(text.includes(marker))text=text.slice(0,text.indexOf(marker));fs.writeFileSync(card,text+marker+`\n[[atlas/! themes/_research/${t.slug}|Разбор исходников ${t.name}]] — ${news.length} новых карточек, ${olds.length} подтверждений существующих приёмов.\n`);
}
const pairCount=new Set(findings.map(f=>f.id+'|'+f.theme)).size,represented=new Set(findings.map(f=>f.theme)).size;
const pending=coverage.reduce((n,t)=>n+t.settings.filter(s=>s.disposition==='candidate-not-yet-deduplicated').length,0);
const overview=`# Исследование 100 тем\n\nДата: 2026-09-16. Исходная сотня зафиксирована в картотеке по скачиваниям; это не новая выборка.\n\n## Полученные результаты\n\n- 100 репозиториев получены и привязаны к commit.\n- ${coverage.reduce((n,t)=>n+t.docs.length,0)} Markdown-документов инвентаризировано; ${coverage.reduce((n,t)=>n+t.ruleCount,0)} правил основного CSS разобрано.\n- **${added} новых карточек** с объяснением отличия от исходного каталога. Это возможности тем, без непроверенных применяемых сниппетов.\n- Подтверждениями дополнены **${updated} существующих карточек**.\n- **${pairCount} пар «приём — тема»** подтверждены в этом проходе, охватывают **${represented} тем**. Несколько доказательств для одной пары не увеличивают счётчик.\n- Существующие источники и CSS-рецепты сохранены.\n\n## Завершённый объём и ограничения\n\nПроверены **100 из 100 тем** исходной выборки. Реестр содержит **${coverage.reduce((n,t)=>n+t.settings.filter(s=>['class-toggle','class-select'].includes(s.type)).length,0)} переключателей и списков вариантов**; все получили результат. Остаток очереди: **${pending}**. В продолжении разобраны все 1266 ранее отложенных настроек, включая палитры, типографические параметры и служебные пункты.\n\nЭто завершённый разбор зафиксированных исходников, а не гарантия обнаружения каждого возможного сочетания CSS. Проверены основной CSS, объявления настроек и текстовые инструкции; 373 Markdown-файла входят в инвентаризацию, среди них также changelog, лицензии и шаблоны issues. Внешние сайты, отдельные demo-vault и скриншоты не входят в закрываемый реестр. Визуальная проверка в установленном Obsidian не проводилась. У 4 тем строгий CSS-парсер встретил ошибки: засчитаны только отдельно разобранные правила; исходник и ограничение указаны на странице темы.\n\n**Flexoki** — особый результат, а не пропуск: основной CSS содержит две палитры, без самостоятельных правил компоновки. У остальных 99 тем найдены подтверждённые связи с приёмами. Устаревшие настройки без текущего CSS помечены отдельно; они не рекламируются как работающие возможности.\n\nИтоги 1266 решений: ${Object.entries(decisions.reduce((a,d)=>(a[d.outcome]=(a[d.outcome]??0)+1,a),{})).map(([k,v])=>(k==='mapped'?'связано с карточками':outcomes['reviewed-'+k])+' — '+v).join('; ')}. Все решения и ссылки доступны на страницах тем.\n\n## Новые карточки\n\n${defs.filter(d=>d.id&&findings.some(f=>f.id===d.id)).map(d=>`- [[atlas/! hacks/${d.id}/${d.id}|${d.title}]]`).join('\n')}\n\n## Покрытие по темам\n\n| № | Тема | Новые | Существующие | Без результата |\n|---|---|---:|---:|---:|\n${coverage.map(t=>`| ${t.rank} | [[atlas/! themes/_research/${t.slug}|${t.name}]] | ${new Set(findings.filter(f=>f.theme===t.slug&&!f.existing).map(f=>f.id)).size} | ${new Set(findings.filter(f=>f.theme===t.slug&&f.existing).map(f=>f.id)).size} | ${t.settings.filter(s=>s.disposition==='candidate-not-yet-deduplicated').length} |`).join('\n')}\n`;
fs.writeFileSync(path.join(research,'! обзор.md'),overview);
const reproduction=`\n## Воспроизведение\n\nЗафиксированные репозитории и commit находятся в inventory.json. Исходники временно лежат в /tmp/hacksidian-theme-survey; в проект не копируются. fetch.py повторно использует зафиксированные commit.\n\n1. Установить зависимости plugin согласно проекту.\n2. Выполнить python3 tools/theme-survey/fetch.py.\n3. Выполнить node tools/theme-survey/index.mjs (полный индекс создаётся в /tmp).\n4. Сопоставления заданы в tools/theme-survey/features.json, static-rules.json и docs/research/theme-survey/decisions.json; проверять и настройку, и действующую реализацию, а для примеров — документ и CSS.\n5. Выполнить node tools/theme-survey/review.mjs, затем node tools/theme-survey/document-review.mjs и node tools/theme-survey/publish.mjs /path/to/atlas.\n6. Выполнить node tools/theme-catalog/build.mjs /path/to/atlas.\n7. Проверить node tools/theme-survey/verify.mjs, node tools/verify-recipe-catalog.mjs и node plugin/scripts/catalog-check.mjs.\n\ncoverage.json содержит полный извлечённый реестр настроек, findings.json — опубликованные доказательства. decisions.json содержит обоснования всех 1266 решений продолжения; remaining.json пуст. documentation-review.json хранит хеши документов и итог по каждой теме. Отчёты не индексируются как карточки приёмов. Перед расширением правил сопоставления проверяйте ложные совпадения: CSS настроек самого Style Settings, обратные переключатели, мобильные условия, вложенные селекторы и правила-исключения.\n`;
fs.writeFileSync(path.join(dir,'README.md'),overview+reproduction);
console.log(JSON.stringify({added,updated,pairCount,represented,pending}));

const atlasIndex=path.join(atlas,'atlas.md');
if(fs.existsSync(atlasIndex)){
 let index=fs.readFileSync(atlasIndex,'utf8');const marker='\n## Новые приёмы из исследования тем — 2026-09-16\n';
 if(index.includes(marker))index=index.slice(0,index.indexOf(marker));
 const list=defs.filter(d=>d.id&&findings.some(f=>f.id===d.id));
 fs.writeFileSync(atlasIndex,index+marker+'\nНиже — возможности тем, подтверждённые по исходникам. Условия и примеры находятся в карточках; независимых применяемых CSS-рецептов у этих карточек пока нет.\n\n[[atlas/! themes/_research/! обзор|Покрытие исследования и источники]]\n\n'+list.map(d=>`- [[atlas/! hacks/${d.id}/${d.id}|${d.title}]]`).join('\n')+'\n');
}
